### ISSUE TITLE
add commit data to $git

### ISSUE THREAD

**Issue by safazi** [roblox-aurora/rbxts-transform-debug#4]
`$git` should also include the date, either as a timestamp or a string.

**Comment by Vorlias** [comment]
The date of the commit itself, or the current date (at time of compile)?

**Comment by Vorlias** [comment]
I'll will add `$git.DateTime` - which will be the result of `git show -s --format=%ct` formatted as an ISO 8601 date (e.g. `2022-01-03T12:18:41.000Z`) which can be passed to Roblox's `DateTime.fromISODate`.
