### ISSUE TITLE
Support PKG_VERSION

### ISSUE THREAD

**Issue by Dionysusnu** [roblox-aurora/rbxts-transform-debug#7]
With roblox-ts/roblox-ts#1990 removing this, rbxts-transform-debug seems like a good fit to replace it. Maybe with a different name, like $pkgVersion or $packageVersion?

**Comment by Dionysusnu** [comment]
Or maybe this belongs as part of dictionary returned by `$git`?

**Comment by Vorlias** [comment]
> Or maybe this belongs as part of dictionary returned by `$git`?

No, `$git` should stay as anything related to git. it would likely be `$packageVersion`, or even potentially preset fields from package, similar to `$git`. like `$package.Version`.

**Comment by Vorlias** [comment]
Supported now as part of `$package.version`.
